core.entity_form_display.node.article.default:
  expected_config:
    content:
      field_content:
        settings:
          add_mode: modal
      field_meta_tags:
        settings: {  }
  update_actions:
    add:
      content:
        field_content:
          settings:
            features:
              add_above: '0'
    change:
      content:
        field_content:
          settings:
            add_mode: dropdown
        field_meta_tags:
          settings:
            sidebar: true
