core.entity_view_display.node.article.default:
  expected_config:
    content:
      field_content:
        weight: 1
      field_meta_tags:
        label: above
        region: content
        settings: {  }
        third_party_settings: {  }
        type: metatag_empty_formatter
        weight: 3
      links:
        weight: 2
    hidden:
      field_social_sharing: true
  update_actions:
    delete:
      content:
        field_meta_tags:
          label: above
          region: content
          settings: {  }
          third_party_settings: {  }
          type: metatag_empty_formatter
          weight: 3
      hidden:
        field_social_sharing: true
    add:
      hidden:
        field_meta_tags: true
    change:
      content:
        field_content:
          weight: 2
        field_social_sharing:
          label: hidden
          region: content
          settings: {  }
          third_party_settings: {  }
          type: social_media_default
          weight: 1
        links:
          weight: 3
